### ISSUE TITLE
Raphaël JS gegen eine schmalere Lib tauschen

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/statify#1]
Für die aktuelle Darstellung der Statistik wird Raphaël JS verwendet - insgesamt kommt die Bibliothek auf fast 100 KB an JavaScript. Alternativen wie http://www.chartjs.org kommen auf die Hälfte.

Die Frage bleibt, ob die Alternative den aktuellen (visuellen) Funktionsumfang abbilden kann.

**Comment by ghost** [comment]
I'd probably be able to implement something like this. Could you tell why this project moved from Google's to Raphaël's library in the past?

**Comment by websupporter** [comment]
To use another library and therefore another method to display the tooltips might help us to walk around current problems, we experience with the tooltips, see https://github.com/pluginkollektiv/statify/issues/28

But, if I am not mistaken chartJS currently uses 140KB in the minified version?

**Comment by patrickrobrecht** [comment]
My plugin [Extended Evaluation for Statify](https://wordpress.org/plugins/extended-evaluation-for-statify/) provides diagrams and tables for the Statify data using the [Highcharts](http://www.highcharts.com/). This is not really a more lightweight library, but it has additional features like export of the diagrams.

**Comment by bueltge** [comment]
I think we should use [Flot](http://www.flotcharts.org/), The library is a addon for jquery. jQuery is a part of the core of WP and always active in the back end. The library is small and have all functions, there we need. The library is also possible to work responsive, incl. a [resize](http://stackoverflow.com/a/17243050/730125) have all views a live update.
