### ISSUE TITLE
Long loading time for our JS snippet

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#100]
>1s loading time for or XMLHTTPRequest `/?statify_referrer=&statify_target=%2F `
https://wordpress.org/support/topic/ladezeit-problem/

This is an asynchronous request, so this shouln't slow down the website, but why is this happening at all?

![bildschirmfoto 2018-07-31 um 13 50 14](https://user-images.githubusercontent.com/870475/43457991-cc40bfa0-94c8-11e8-80c8-2db7e9c0e9d1.png)

![bildschirmfoto 2018-07-31 um 13 50 36](https://user-images.githubusercontent.com/870475/43457980-bd3f2c58-94c8-11e8-812e-8dfda6cdf5cf.png)

**Comment by stklcode** [comment]
Can't reproduce this issue on multiple sites, RTT always in range of 50-100ms...

Best guess is that some other plugin is doing heavyweight operations before Statify kicks in in the `plugins_loaded` phase. Page generation time without a cache (seems _WP Fastest Cache_ is active) would be intersting here.

As also mehtioned in the forums, the targeted site has an average page load time (TTFB) of over 1s (tops out around 2.5s) for yet uncached pages (observed by clicking through the menus). I'd say slow server or heavy plugin activities and not a Statify issue.

**Comment by stklcode** [comment]
Based on my observations, I don't think we have a major performance issue here.

Nevertheless, we could investigate in refactoring or JS tracking to e.g. the AJAX endpoint to not waste time for other plugins and operations when tracking is the only action of interest.

**Comment by Zodiac1978** [comment]
@stklcode Should this ticket stay open for the refactoring idea or do you want to open another ticket for this?

**Comment by stklcode** [comment]
Hard to tell. Actually the reported "behavior" is not really an error. But what else would we write into a new issue, so I'd keep it open for now...

I played around with switching to AJAX API calls couple of weeks ago that reduces load time of the JS call. Obvious, most plugins opt-out or at least do much less work on these calls and the template is not parsed. I'll prepare a PR for discussion on that soluition.

**Comment by patrickrobrecht** [comment]
After merging #109 a WP AJAX call is used, which hopefully fixes the problem.
