### ISSUE TITLE
Action hooks not documented

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#102]

**Comment by patrickrobrecht** [comment]
`statify__skip_tracking` und `statify__user_can_see_stats` sind auf https://wordpress.org/plugins/statify/ bzw. in der [readme.txt](https://github.com/pluginkollektiv/statify/blob/master/readme.txt) dokumentiert, der <del>Filter</del> Action Hook `statify__visit_saved` hingegen nicht.

**Comment by Zodiac1978** [comment]
In der Dokumentation stehen die *Filter* Hooks. 

Nicht dokumentiert sind die *Action* Hooks, also `cachify_flush_cache` und eben `statify__visit_saved`.

`cachify_flush_cache` könnte man ja auch nutzen, um andere "purge cache" Funktionen dranzuhängen.

Wäre auch die Frage, ob das so herum überhaupt Sinn macht. Wäre es nicht schlauer dort einen generischen Action Hook zu benutzen, der den Ort korrekter beschreibt und dann (sofern die Funktion/Klasse existiert) die Cachify-Funktion an den Hook zu hängen. Aktuell wird das ja in Cachify selbst an den Hook gehängt.
https://github.com/pluginkollektiv/cachify/blob/3ce1b2063441378476ac140c3bdcb8d036afc042/inc/cachify.class.php#L102-L108

Analog könnte man so noch mehr Cache-Plugins unterstützen, sofern eine öffentliche Funktion für das Löschen des Cache existiert.

Und für `statify__visit_saved` könnten wir meinen Gist weiter verbessern:
https://gist.github.com/Zodiac1978/8fbf5d67063cb213f530812d0f5b247d
Der machte bei DomainFactory auf jeden Fall Probleme. Das SQL-Statement muss nochmal überarbeitet werden.

**Comment by stklcode** [comment]
`statify__skip_tracking` is documented rather incomplete. Strictly speaking the hook is not of type `boolean`, but `boolean|null` or `?bool` and it is definitely not clear from the wiki that returning `false` is equal to whitelisting the current request without evaluating any builtin filters.

**Update:** I just extended the documentation for all 3 possible return values, consider this point done.

**Update 2:** Also added documentation for `statify__visit_saved` in the Wiki

**Comment by patrickrobrecht** [comment]
Thanks to @stklcode, `statify__visit_saved` is documented: https://statify.pluginkollektiv.org/de/documentation/hooks/#visit_saved and https://statify.pluginkollektiv.org/documentation/hooks/#visit_saved, so I close this issue.

The same holds for cachify_flush_cache: https://cachify.pluginkollektiv.org/de/documentation/hooks/#flush_cache and https://cachify.pluginkollektiv.org/documentation/hooks/#flush_cache.
