### ISSUE TITLE
Add option on settings page to show stats for different roles

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#106]
A filter is sometimes scary for beginners. Why not adding this as an option on the settings page?
https://github.com/pluginkollektiv/statify/wiki/en-Hooks#statify__user_can_see_stats

Are there any reasons why this should not be done?

**Comment by stklcode** [comment]
Can't see any point against that. Would not overload the dashboard Widget however, yet another point for adding a dedicated settings page.

**Comment by Zodiac1978** [comment]
> yet another point for adding a dedicated settings page.

People sometimes miss the configuration page at all (see: https://www.internetkurse-koeln.de/wordpress-statistik-statify-versus-google-analytics-und-co/ at the bottom "Nachtrag").

How about moving the whole setting for the dashboard widget/Statify to an own settings page?

As a fallback we could leave a link to the new settings page on the dashboard widget config page.

**Comment by stklcode** [comment]
> How about moving the whole setting for the dashboard widget/Statify to an own settings page?

Like so?

![statify_106_screenshot2](https://user-images.githubusercontent.com/12963621/46407169-3bb53100-c70e-11e8-83cc-a526e4be20b2.png)
![statify_106_screenshot1](https://user-images.githubusercontent.com/12963621/46407168-39eb6d80-c70e-11e8-8de8-256cf23207c2.png)

(not a mockup, fully funcitonal local fork)

**Comment by Zodiac1978** [comment]
Wow. Just wow! 💯 🥇

**Comment by Zodiac1978** [comment]
What about using this UI for our settings:

<img width="651" alt="Bildschirmfoto 2021-11-13 um 20 52 50" src="https://user-images.githubusercontent.com/870475/141657298-a63e546c-f8b6-499d-b7d6-d576c4e05de6.png">

The list of user roles is, of course, dynamic and lists all registered user roles in the current WP install.

**Comment by RalfRoemling** [comment]
Anything new on this one? I have exactly this usecase not working at the moment and would have to escalate roles of my Editors to Admin.

**Comment by Zodiac1978** [comment]
@RalfRoemling If you are comfortable to add some code (via functions.php, functionality plugin or code snippets plugin, you can use the code mentioned on the hook documentation:
https://statify.pluginkollektiv.org/documentation/hooks/#user_can_see_stats

**Comment by RalfRoemling** [comment]
Yep, read that already in the older posts but a GUI solution would be more comfy and clearer in it's intention :-)

**Comment by ghost** [comment]
Oh, just seen this. Will this make it into the next release? When can we expect it?
Thanks for the work!

**Comment by RalfRoemling** [comment]
Yep, absolutely great. Thx a lot for implementing! Much appreciated 👍
