### ISSUE TITLE
Add new column for country

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#107]
We could use https://ip2country.info with a shortened IP to get the country and provide the country information too.

With #104 this could maybe clutter the dashboard widget, so maybe we should talk about adding an own page for this.

@patrickrobrecht What do you think?

**Comment by stklcode** [comment]
-1 from my POV.

No matter how much we argue about shortened addresses we should keep our line to collect and transmit no personal data. 
Not every user is aware on the impact of shortened IPs, I can already hear the voices telling "Statify transmits addresses and is now evil"....
Also StartPage + Country + Mobile + x? leads to generate a more and more precise picture of the actual user, at least on low-usage sites with international target group.

Maybe as Opt-In or even separate extension

**Comment by websupporter** [comment]
I see the point of @stklcode. Actually, with the `statify__visit_saved` a 3rd party could hook in to collect this data if needed :thinking: 

> Also StartPage + Country + Mobile + x? leads to generate a more and more precise picture of the actual user

To me this leads to a very fundamental question about in what direction we might want to develop Statify further. What I mean, its quite easy for each of those to say "yeah, that’s a nice idea and would give us interesting data without any privacy issue" and step by step we could end up adding a lot of data points which combined would be quite powerful again.

_from the guy who started this issue on twitter... _ :D

**Comment by Zodiac1978** [comment]
> No matter how much we argue about shortened addresses we should keep our line to collect and transmit no personal data.

Yes, that's my opinion too, at least for the country information. I'm just trying to collect every idea which was mentioned somewhere to get a better picture what people are missing in Statify at the moment.
See: https://gist.github.com/Zodiac1978/44ef90947fc320660688214af2936a01

> Also StartPage + Country + Mobile + x? leads to generate a more and more precise picture of the actual user, at least on low-usage sites with international target group.

Yes, and our main audience are smaller blogger with no international audience, so the information would be not very helpful (in relation to something like mobile vs. desktop usage.

> Actually, with the statify__visit_saved a 3rd party could hook in to collect this data if needed

I tried this way with the mobile/desktop information but was struggling. Maybe we could build a sample for this, people could use as a starting point to gather more information if needed?

**Comment by websupporter** [comment]
On the other hand, _I mean, just throwing ideas in my head_, why do we think of those information as connected (like indicated in the title "Add new column for country", which I assume is a database column.

We could collect this data also like
`"update wp_statify_countries set count+=1 where code='de'"`
or `update_option('statify_mobile_usage', $mobile_usage + 1)`

_edit: ah, this goes out of joint, when to delete this data, would need a timestamp, so its connected, hmm, but maybe there is a way to explore_

I mean, there are some path you could go, which keeps the data in a state which can hardly be mixed together and still prove something like "you do not need to track your visitors to death just to get a nice map from where they are coming and if they are using their smartphone and..."

I could see Statify as trying to make such a point maybe?

**Comment by Zodiac1978** [comment]
If you just have one visitor from Belgium as commenter for example this could nevertheless lead to an identifiable information. This isn't the case for mobile vs. desktop.

**Comment by websupporter** [comment]
Belgium has 11 million inhabitants?! I mean, we all know, it must be @ginocremer, but XD

On a serious note, so he left a comment, which means he left identifiable information like his email address and actually also his ip (wp core default behavior). If you comment, you are to a certain degree identifiable by choice imo.

**Comment by Zodiac1978** [comment]
Yes, but you could have an anonymous comment without en email which states he/she is from Belgium and you just have one visit ... okay this gets a little bit "constructed" ...

The question remains: Do our users need/want this feature? Mobile vs. Desktop is heard much more often than country ... so I wouldn't give a high priority at the moment.

**Comment by patrickrobrecht** [comment]
I agree with @stklcode that Statify should continue to be as privacy-friendly as possible and transmitting the (shortened) IP address to some "IP to country converter" isn't.

I think an `isMobile` column (#104) is much more interesting for most users.
