### ISSUE TITLE
Should we respect the Do-not-track header?

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#108]
No, this is about tracking of individual users which is not done by Statify.
See: https://en.wikipedia.org/wiki/Do_Not_Track

**Comment by stklcode** [comment]
> [...] disable either its tracking or cross-site user tracking (the ambiguity remains unresolved) of an individual user.

We do not track "individual users", but simply count requests that are treated independently.

So I'd vote for keep ignoring.

However if we decide on a settings page in #103 we might include "Exclude DNT" as an Opt-In feature to let the administrator decide.
