### ISSUE TITLE
Refine the user agent check

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#112]
> Statify comes with a default filter that whitelists Windows, Linux, iPhone, etc.
> The mobile bots however match this to force mobile display instead of desktop version.
>
> Mozilla/5.0 (iPhone; CPU iPhone OS 8_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B411 Safari/600.1.4 (compatible; YandexBot/3.0; +http://yandex.com/bots) — Indexing robot.
>
> This behavior should probably be changed in future versions to a more refined blacklist.
>
> Currently the only chance is a custom skip hook or a blacklist plugin to filter their IP subnet. (my blacklist extension does not feature user agent filter either at the moment)

There is a bot from a French search engine which is using "Linux" in his user agent:
https://regex101.com/r/xZALC3/1/
Exabot - https://www.keycdn.com/blog/web-crawlers

Because of this problem and the problem mentioned above about mobile user agents we should blacklist the most used bots too.

I found a great resource of bots with regex patterns to detect and blacklist many bots.
https://github.com/monperrus/crawler-user-agents

**Comment by stklcode** [comment]
Exclude the word “bot“ in addition to the current filter works quite well on another system where I implemended a similar statistics processor on my own. (shame on me I never contributed back :see_no_evil: )
I got a PHPUnit Test somewhere with about 50 known bot strings. Think we should add such checks here, too.

**Comment by Zodiac1978** [comment]
This is a very basis regex blacklist which should detect most of them:
https://gist.github.com/geerlingguy/a438b41a9a8f988ee106

**Comment by mahype** [comment]
I have enhanced the bot detection by using the gist given by @Zodiac1978.

**Comment by Zodiac1978** [comment]
@mahype This ticket can be closed after #125 is merged. Correct?
