### ISSUE TITLE
Check for Gutenberg compatibility

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/statify#115]
WordPress 5.0 will be here soon. Time for us to check, if our plugins are compatible with the Gutenberg Editor and WP 5.0 (a beta version is yet to be published). 

- [x] check (Gutenberg) editor with this plugin
- [x] check plugin settings site with active Gutenberg
- [x] fix potential issues
- [x] add `Tested up to: 5.0` to the plugins readme
- [ ] publish changes as minor update or with upcoming plugin update

**Comment by Zodiac1978** [comment]
With the latest iteration of WP 5.0 I get this error message in our dashboard widget:
> This meta box, from the Statify plugin, isn't compatible with the block editor.

**Comment by Zodiac1978** [comment]
<img width="616" alt="bildschirmfoto 2018-10-24 um 23 00 55" src="https://user-images.githubusercontent.com/870475/47461287-bbe82700-d7e0-11e8-8e1b-83d2d696149f.png">

**Comment by krafit** [comment]
Ehm, the Dashboard Widget is Not compatible with the Editor?! That’s... strange 🤔

**Comment by websupporter** [comment]
Seems more like a WP core bug in the beta?

**Comment by websupporter** [comment]
https://core.trac.wordpress.org/ticket/45112#comment:12 here we go.

**Comment by Zodiac1978** [comment]
Closed my ticket as duplicate: https://core.trac.wordpress.org/ticket/45173
Thanks for the link @websupporter !

**Comment by websupporter** [comment]
Has been resolved in the current beta 2 (see https://core.trac.wordpress.org/changeset/43839, https://core.trac.wordpress.org/ticket/45207)
![grafik](https://user-images.githubusercontent.com/6458412/47725091-99cb2a80-dc60-11e8-835d-c6fce03736f0.png)
