### ISSUE TITLE
Support link is not translatable

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#122]
We have a translatable link to our plugin:
https://github.com/pluginkollektiv/statify/blob/10edcff202601be9714bb032f8260ec758dccef4/views/widget-back.php#L42

But not translatable to our support forum:
https://github.com/pluginkollektiv/statify/blob/10edcff202601be9714bb032f8260ec758dccef4/views/widget-back.php#L44

**Comment by chesio** [comment]
Here's one more Support link that could be translatable:
https://github.com/pluginkollektiv/statify/blob/f7985e3dba345415f7ddb9542557079a9dedc74e/inc/class-statify-backend.php#L43
