### ISSUE TITLE
Does not track, cant find the issue - can somone help me?

### ISSUE THREAD

**Issue by tobiasvielmetter** [pluginkollektiv/statify#131]
Hi, I am trying to use statify on https://haubrok.org. I am using it with W3 total cache plugin and and stack path cdn. Somehow I cant get it to track. I have enabled JS tracking, but the xmlrequest is fired seemingly without paramteters and returns the entire page and does not track.

Can somone point me in the right direction? I somehow cant seem to find the issue. Is this something I need to configure with w3 total cache plugin?

Oddly I have several wordpress pages based ont he same theme that work without any issue.

Thanks for any pointers!

**Comment by stklcode** [comment]
The tracking-request is cached.

![statify-131](https://user-images.githubusercontent.com/12963621/64800190-68143700-d586-11e9-92b8-2653854eb97d.png)

Request parameters are fine. I visited the home page directly, so target `/` (or `%2F` after encoding) is correct and no referrer is expected.

Statify obviously cannot execute anything if the site is served from disk cache. With currelt stable release of Statify you must exclude the request from caching in some way, either by excluding requests with URL parameters (you most likely don't need them to be cached with your URL scheme) or by some more refined rules.
W3 Total Cache should have some option to enable/disable caching of URIs with query strings (cannot remember the exact wording here).

**Comment by tobiasvielmetter** [comment]
@stklcode Thank you so much for looking into it. What you report makes complete sense. As far as I understand W3 Total Cache does not cache pages with query strings (there are not settings for excluding query strings from the cache, but the other way around: I can add stuff to the cache with specific query strings).
I have now turned off the cache plugin entirely, purged all caches beforehand and reloaded and there is still no tracking. Unfortunately I don't seem be able to get the same information about the page being delivered from the cache, as you did in your screenshot. Is this with a specific plugin? I always get a normal 200 response for all requests, also the XHR requests.
I am still at a loss... something seems to interfere with the plugins ability to track and I can't identify what it is.

**Comment by stklcode** [comment]
> As far as I understand W3 Total Cache does not cache pages with query strings (there are not settings for excluding query strings from the cache, but the other way around: I can add stuff to the cache with specific query strings).

There used to be a switch to control this behavior, called "Cache URIs with query string variables"
(see https://stylemixthemes.com/wp/guide-to-w3-total-cache/ ) Haven't used the plugin for quite a while though, so it may be obsolete. But this is quite a common option which is available in any other caching plugin I've used so far.

> I have now turned off the cache plugin entirely [...]

The Statify request still shows response status "301 (from disk cache)"...

**Comment by tobiasvielmetter** [comment]
Thanks @stklcode for looking at it again. I am not sure right now why there is still some caching (maybe this is hosting related). It does not seem to be related to the W3 total cache... 
The option you pointed on in W3 Total Cache is greyed out and not available, not sure why its shown in the interface (and its turned off too).

Thanks again. I will report when I find a solution. If anyone has a pointer that could help me, Id appreciate it.

**Comment by Zodiac1978** [comment]
@tobiasvielmetter Any news from your side? Disabling W3 Total Cache is not an easy task:
https://www.thewebmaster.com/wordpress-articles/how-to-uninstall-w3-total-cache-manually/

**Comment by tobiasvielmetter** [comment]
@Zodiac1978 I have not found a real solution for this yet. AFter spending more than a day on it I have given up for now. If you have any pointers let me know. Technically W3 total cache should not be the issue, but who knows.

**Comment by Zodiac1978** [comment]
@tobiasvielmetter Still using Statify? Any new insights?

**Comment by patrickrobrecht** [comment]
Closed due to missing feedback.

@tobiasvielmetter Feel free to reopen if you've any new insights.

**Comment by tobiasvielmetter** [comment]
Thanks, I haven't been working with this anymore. Sorry.
