### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by StephanieWiermann** [pluginkollektiv/statify#14]

**Comment by StephanieWiermann** [comment]
Copy from readme.txt

**Comment by Zodiac1978** [comment]
What about this chrome app note? Link is not working anymore. App was never in Web Store. Should we remove the line/link?
"Speziell für Chrome-Browser entwickelte Statify App"

**Comment by glueckpress** [comment]
+1 remove

**Comment by Zodiac1978** [comment]
The line is in CHANGELOG.md too - but why do we have this single changelog.md?

**Comment by StephanieWiermann** [comment]
Don´t know, never noticed it, was to focused on my tasks ;) Is there a reason to keep it? Or can we get rid of changelog.md?

**Comment by swissspidy** [comment]
It's considered best practice to have a separate changelog file.

There's also another reason: When the readme file gets too long (like, hundreds of lines), WordPress.org can't handle it anymore and strips off text. In that case, only the most recent versions should be added to the readme, and the whole changelog should be in the separate file.

Here's a good example: https://github.com/Yoast/wordpress-seo/blob/trunk/readme.txt#L418

The changelog section only contains the last few versions (still too many IMHO) and then references https://github.com/Yoast/wordpress-seo/blob/trunk/changelog.txt.

Edit: See also http://keepachangelog.com/
