### ISSUE TITLE
Heavily more visitors since v1.7.0

### ISSUE THREAD

**Issue by MatzeKitt** [pluginkollektiv/statify#149]
I noticed that there are many more visitors on my website since v1.7.0. This seems cool, but I was a little bit pessimistic and thus looked into the server logs.

I noticed that the Icinga uptime check is no more recognised as bot and thus its requests get counted. It seems that this is because the removed check for `Mozilla` in the user agent.

This is a request:
```
46.xx.xx.xx - - [11/May/2020:00:00:05 +0200] "GET / HTTP/1.0" 200 53211 "-" "check_http/v2.2 (monitoring-plugins 2.2)"
```

It would be nice to have such identifiers also in the `is_bot()` method.<br>
And it would be also nice to be able to filter these identifiers to add/remove them depending on your need.

**Comment by stklcode** [comment]
Good catch!

Regression form #125 
We should either re-add a reasonable whitelist or add “check“ and/or “monitor“ to the blacklist. Sounds familiar from Nagios/Icinga modules...

Btw. _PRTG_ Monitoring add this line:
`Mozilla/5.0 (compatible; PRTG Network Monitor (www.paessler.com); Windows)`
So +1 for “monitor“. This would have passed the 1.6 whitelist (Windows, Mozilla).


For dynamic user-defined blacklists there is an extension-plugin _Statify Blacklist_ (disclaimer: my plugin). You can at least temporarily block the Monitoring IPs (UA is on my wishlist).
We might discuss whether to merge both functionalities into _Statify_ in future releases.
Until then you can only utilize a custom `statify__skip_tracking` Hook...
