### ISSUE TITLE
Superflous period in description

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#153]
> Das Aktivieren dieser Option schließt alle Aufrufe mit Verweisen aus der Kommentar-Blacklist vom Tracking aus..

We should be more consistent with periods. Including or not including them ...

https://github.com/pluginkollektiv/statify/blob/3c4cbce44b74b5569a46ccc4b991a01a2366327e/inc/class-statify-settings.php#L230

vs. 

https://github.com/pluginkollektiv/statify/blob/3c4cbce44b74b5569a46ccc4b991a01a2366327e/inc/class-statify-settings.php#L244

I don't have a strong opinion which is better, but we should choose one variant and stay with it to avoid double periods as seen now in the German translation.

**Comment by abrain** [comment]
I'd argue, the period and all other punctuation marks should be part of the translatable string as [they are language-specific](https://en.wikipedia.org/wiki/Punctuation#Other_languages). Also, adding characters/words on either side of a string does not work for scripts written from right to left.

**Comment by Zodiac1978** [comment]
Good point @abrain !

Now I have a strong opinion. We should always include them. :)
