### ISSUE TITLE
Refresh button for the dashboard widget

### ISSUE THREAD

**Issue by tthemann** [pluginkollektiv/statify#157]
Up to 1.7.0, opening the options dialog and saving options w/o any change deleted the transients. During testing, I (mis-)used that as a "refresh statistics immediate" functionality. Since 1.7.1, the transients are only deleted if an actual change has been made and I´m missing the "refresh" (actually, I´m just too busy to wait 4 minutes ;-) ). Wouldn´t it be handy to have some sort of "refresh" link in the dashboard widget?

**Comment by stklcode** [comment]
We already thought about that as well (see discussion in #148), but decided as against preserving this feature.
Saving the options as replacement for a real "refresh" button was never actually documented and intended to be used in that way, but let's confess, we all have used it many times.

+1 for a refresh button in the widget backview to make it explicit.

**Comment by chesio** [comment]
If this is implemented, I would argue that the default transient lifetime should be increased to more than 4 mins :-)
