### ISSUE TITLE
Broken stats after update to 1.8

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#179]
It looks like there something broken with version 1.8 (at least in my install):
![Bildschirmfoto 2020-08-09 um 21 46 49](https://user-images.githubusercontent.com/870475/89740552-f096a280-da89-11ea-94be-61d791f5009e.png)

Any ideas what happened here? @patrickrobrecht @stklcode

**Comment by patrickrobrecht** [comment]
I cannot reproduce the error. @Zodiac1978, do you see any errors on the console?

**Comment by Zodiac1978** [comment]
Maybe just a hiccup on my side. After looking for errors in the console everything is fine again ...
