### ISSUE TITLE
No action shown in WP Crontrol

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#184]
First reported here: https://wordpress.org/support/topic/no-action-for-statify_cleanup/

I can reproduce this on my website. There is "none" showing for teh action in WP Crontrol for the `statify_cleanup` function scheduled daily. Per documentation from WP Crontrol this could be a bug:

> An event with no action is also useless, although there is a small chance that an action gets conditionally added to this event by a plugin based on a setting, for example, and thee plugin isn’t correctly handling the scheduling or unscheduling of the event.

On the other side BackWPup and Antispam Bee have the same warning ...

Maybe because we add this in a private function?

**Comment by stklcode** [comment]
The answer is suprisingly simple: We only register the Cron action during Cron execution.

https://github.com/pluginkollektiv/statify/blob/23f9e3648957b17bb91cba77419e043ed87098bd/inc/class-statify.php#L68-L70

So it works and it can be triggered manually. However in the _WP Control_ interface, we got a regular admin request. Nevertheless the Cron task works fine when triggered, so only the UI is affected here.

We can
1. always register the `statify_cleanup` action or
2. register the `statify_cleanup` action both for cron and for admin requests (regular requests, AJAX, etc. will likely never use it)

**Comment by Zodiac1978** [comment]
I am fine with changing nothing but documenting it somewhere.
