### ISSUE TITLE
Übersetzung ins Englische

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/statify#2]
Wie abgemacht, bitte die Übersetzungen in der Sprachdatei kontrollieren bzw. editieren.

Wenn noch Zeit und Lust da sind, bitte auch die Datei _readme.txt_ ins Englische übersetzen, damit der Plugin-Beschreibungstext im offiziellen WordPress-Pluginverzeichnis in Englisch dargestellt wird. Die Datei _README.md_ bleibt weiterhin in Deutsch, damit Nutzer ohne Englischkenntnisse hier auf Github konsumieren können.

Lieben Dank!

**Comment by pixolin** [comment]
Autsch, wer lesen kann ist klar im Vorteil. Hab jetzt die README.md um
die englische Übersetzung ergänzt. Sorry …

Bego

Am 16.04.15 um 10:09 schrieb Sergej Müller:

**Comment by sergejmueller** [comment]
Ist alles kein Problem - schönen Dank dafür!

Wenn du noch über die [Sprachdatei](https://github.com/sergejmueller/statify/blob/1.4.0/lang/statify-de_DE.po) schauen magst, dann wären wir auch schon durch mit Englisch ;)

**Comment by pixolin** [comment]
Hab ich schon, finde die Übersetzungen alle passend.

Am 16.04.15 um 13:59 schrieb Sergej Müller:

**Comment by sergejmueller** [comment]
Alles klar. Sehr schön. Bedanke mich.

:metal:
