### ISSUE TITLE
#statify_dashboard css should allow line-wrap.

### ISSUE THREAD

**Issue by ms-studio** [pluginkollektiv/statify#21]
With the new french translation, I notice a css issue on the Statify dashboard: long translation strings extend beyond the visible area of the box.

<img width="597" alt="statify-css-issue" src="https://cloud.githubusercontent.com/assets/241637/10600416/f0e7844e-770a-11e5-9490-ca90dc35f369.png">

The reason why this happens is the `white-space: nowrap;` property, in [css/dashboard.css](https://github.com/pluginkollektiv/statify/blob/ff86f46553b55691df4f4854c02f39d37259b346/css/dashboard.css#L19).

I don't see a reason why that "nowrap" property would be needed. Simply removing it fixes the issue.

**Comment by ms-studio** [comment]
PS: there's also a surprising `height: 1%;` css rule there, wondering what it's use is... Removing it doesn't seem to change anything.

**Comment by swissspidy** [comment]
> I don't see a reason why that "nowrap" property would be needed. Simply removing it fixes the issue.

I don't see a reason either. Will fix it right away.

> PS: there's also a surprising height: 1%; css rule there, wondering what it's use is...

You gotta love magic numbers :) Perhaps we can do a little CSS cleanup here.

**Comment by ms-studio** [comment]
> I don't see a reason either. Will fix it right away.

Awesome!

> You gotta love magic numbers :) Perhaps we can do a little CSS cleanup here.

I assume it was an IE6 css hack or something like that...
