### ISSUE TITLE
Optimize bot detection

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#217]
At the moment we use some string to detect crawler from the user agent string:

https://github.com/pluginkollektiv/statify/blob/667518428b30b0522367fb2c955d1913e1ef672f/inc/class-statify-frontend.php#L222-L236

We could add some more strings, like `seo`, `crawling` and `chrome-lighthouse`
 (borrowed from Koko Analytics):

https://github.com/ibericode/koko-analytics/blob/18716dc9156a83e72b2967cec6dee8ce9acfdbe9/assets/src/js/script.js#L53

Looking at the biggest 10 crawlers, I think we get almost all. But Alexa is missing with their `ia_archiver`.

Maybe something like `fetcher`and `scraper` too ...

`facebookexternalhit` could be another candidate.

Or we could take the big step and use a Third-Party-Library like https://github.com/JayBizzle/Crawler-Detect to detect crawlers.

Another one (in JSON) would be https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json

**Comment by Zodiac1978** [comment]
Additionally we could make these identifiers filterable. Advanced users could extend the list on their own usage/experiences.

**Comment by Zodiac1978** [comment]
Stumbled upon another short variant for bots:
`lighthouse|bot|google|baidu|bing|msn|duckduckbot|teoma|slurp|yandex|crawler|spider|robot|crawling`

**Comment by MatzeKitt** [comment]
`bot` would already include `duckduckbot` and `robot`. And you could summarize `crawler` and `crawling` to `crawl`.

**Comment by Zodiac1978** [comment]
Yes, I know. These are findings on the web. `lighthouse` would also match `chrome-lighthouse`, etc. 

This needs consolidation and decision. I am just sharing other projects solutions to bot detection.

**Comment by Zodiac1978** [comment]
For example: Alexa will be closed on 1st May 2022 (https://support.alexa.com/hc/en-us/articles/4410503838999), so the `ia_archiver` seems to not relevant anymore and does not need to be added.

**Comment by Zodiac1978** [comment]
More user agent strings sorted by software name:
https://developers.whatismybrowser.com/useragents/explore/software_name/

**Comment by florianbrinkmann** [comment]
Using a composer package like https://github.com/JayBizzle/Crawler-Detect sounds like a good idea to me. what do the others think? @2ndkauboy @krafit @pfefferle @stklcode

**Comment by 00Sleepy** [comment]
Implemented Composer Autoload for JayBizzle/Crawler-Detect and replaced bot detection in class-statify-frontend.php with CrawlerDetect function.

Pull request: #247

**Comment by florianbrinkmann** [comment]
Added to the 2.0.0 milestone because the composer package needs PHP 5.3 and we are on PHP 5.2 currently.
