### ISSUE TITLE
Statify REST API Endpoint

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#219]
This issue is meant to be a starting point for discussing the usage of a custom REST API endpoint for tracking and/or showing data.

**Comment by stklcode** [comment]
Why not.

**Tracking:**
For tracking this should be a replacement for the AJAX call we use right now. If there are concerns about compatibility (we know there are some custom JS implementations out there from the AJAX migration), this might be added additionally as fourth/fifth tracking method. Think we do not want to maintain both methods indefinitely though, so AJAX should be at least marked deprecated.

**Visualization:**
The dashboard widget should use this endpoint, so we no longer add the ~JSON~ hidden data table to the markup. We should restrict access to the same user group as for the widget and not open a public endpoint for the world though.
Nevertheless, this endpoint might be reused for frontend visualization (#224) in future releases.
