### ISSUE TITLE
1.4.2 on wordpress.org, missing setting with wp 4.4

### ISSUE THREAD

**Issue by ajgw** [pluginkollektiv/statify#22]
At Wordpress there is still version 1.4.2 for download, why?

And with Wordpress 4.4 the settings of Statify are now missing. Any idea?

**Comment by swissspidy** [comment]
Hi there

This is a bug in WordPress 4.4! See https://core.trac.wordpress.org/ticket/34987 for more information.

It will be fixed in WordPress 4.4.1.

**Comment by swissspidy** [comment]
Oh, and we'll release 1.4.3 on WordPress.org as soon as it's ready.
