### ISSUE TITLE
UTM campaign tracking

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#221]
What about tracking UTM parameters?

Maybe with a limited set of parameters (for example utm_source and utm_campaign)

**Comment by ahoidesign** [comment]
I would like to expand on this suggestion for URL parameter tracking in general.
But an limited set of parameters would also be great (as also clean and reduced)

**Comment by Messa1** [comment]
I like the idea of tracking URL parameter. Would be nice to have such feature.

**Comment by Zodiac1978** [comment]
Hi @Messa1 @ahoidesign 
I don't think this feature will ever land in Statify due to our privacy focus and limited resources. I'm so sorry!

But if you need this, I would like to help and recommend some other plugins at least. Unfortunately this requires the pro version for every plugin I have found:

Koko Analytics Pro is having custom events which could be used for this:
https://github.com/ibericode/koko-analytics/discussions/209
https://www.kokoanalytics.com/kb/tracking-events/

Burst Statistics Pro is advertising with it: "UTM Campaign Tracking: Track the performance of your marketing campaigns."
https://de.wordpress.org/plugins/burst-statistics/

Independent Analytics Pro is having support too:
https://wordpress.org/plugins/independent-analytics/
https://independentwp.com/features/campaigns/

Alternatives are now documented, therefore I will close this issue. If someone wants to help us and build a (privacy compliant) solution, you are welcome to open this again and provide a Pull Request for it.
