### ISSUE TITLE
Overhaul the time functions

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#227]
**Describe the bug**

We track visits in this line:
https://github.com/pluginkollektiv/statify/blob/667518428b30b0522367fb2c955d1913e1ef672f/inc/class-statify-frontend.php#L85

This is explicitly not recommended since WP 5.3:
https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/
https://developer.wordpress.org/reference/functions/current_time/#comment-3414

This saves a WP timestamp (not a correct UNIX timestamp) with `time()` plus timezone adjustments if I understand correctly.

But in https://github.com/pluginkollektiv/statify/blob/667518428b30b0522367fb2c955d1913e1ef672f/inc/class-statify-dashboard.php#L321 we read/compare the data with a PHP date formatted setting (without timezone adjustments). This leads to false data in the dashboard widget.

Additionally `strftime` is deprecated in PHP 8.1 and it is strongly recommended to NOT use it anymore:
https://www.php.net/manual/de/function.strftime.php

This would explain some reports of false data from the support forums.

Maybe there are more errors and deprecations in time functions. Needs more checks.

**Comment by stklcode** [comment]
> we read/compare the data with a PHP date formatted setting (without timezone adjustments). This leads to false data in the dashboard widget.

Actually no.

The transformation used is not elegant in any way (guess it was in a time before PHP `DateTime`), but at least it yields the same results.
The "WordPress timestamp" like a unix-timestamp represents the current epoch seconds, adjusted by timezone offset.

My local system runs on CEST (UTC + 2), so `current_time( 'timestamp' ) - time() === 7200`. So current time 14:30 CEST is transformed to a timestamp equivalent of 14:30 UTC. But the timezone is omitted here, so we effectively get 14:30 local time. So `current_time( 'H:i' ) === strftime( %H:%M', current_time( 'timestamp' ) )`

(Hour/minute example just for demonstration. If the time matches, the date values are the same either.)

Ran a quick verification test on WP test site:



```php
die( 'Unix timestamp: ' . time()  . '<br>' 
   . 'String from Unix timestmap: ' . strftime( '%Y-%m-%d %H:%M:%S', time() ) . '<br>'
   . 'WP timestamp: ' . current_time( 'timestamp' ) . '<br>'
   . 'String from WP timestamp: ' . strftime( '%Y-%m-%d %H:%M:%S', current_time( 'timestamp' ) ) . '<br>'
   . 'WP current time: ' . current_time( 'Y-m-d H:i:s' ) );
```
outputs
> Unix timestamp: 1661431434
> String from Unix timestmap: 2022-08-25 12:43:54
> WP timestamp: 1661438634
> String from WP timestamp: 2022-08-25 14:43:54
> WP current time: 2022-08-25 14:43:54

----

Assuming we want to stay with local date values in the database, we should simply synchronize the notation here, i.e. use the shorter, non-deprecated and more intuitive `current_time( 'Y-m-d' )`  on both ends.
