### ISSUE TITLE
Add option to exclude administrators

### ISSUE THREAD

**Issue by MatzeKitt** [pluginkollektiv/statify#229]
There already is an option to exclude logged in users. However, in environments with e.g. shop systems customers are logged in. So currently you need to decide whether you wand to exclude all logged in users, and thus your customers, too, or none. However, I don’t want to be included as administrator. Thus I would love to have a separate option for that.

Or alternatively, add a multi select with all available roles so that you can pick all roles explicitly, which you want to have excluded.

**Comment by morgenbach** [comment]
absolutely agree. would be very helpful
