### ISSUE TITLE
404 for missing gist links in inline docs

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#24]
Link to line number and file and the missing links:

https://github.com/pluginkollektiv/statify/blob/ff86f46553b55691df4f4854c02f39d37259b346/inc/statify_frontend.class.php#L101
https://gist.github.com/sergejmueller/7612368

https://github.com/pluginkollektiv/statify/blob/ff86f46553b55691df4f4854c02f39d37259b346/inc/statify_dashboard.class.php#L33
https://gist.github.com/sergejmueller/1ce0482c277508d8327e

**Comment by Zodiac1978** [comment]
Wayback Machine just give me the first 10 lines for this:
https://web.archive.org/web/20131209172623/https://gist.github.com/sergejmueller/7612368
`<?php

add_filter(
    'statify_skip_tracking',
    function() {
        //if (  ) {
            return true;
        //}
    }`

**Comment by 2ndkauboy** [comment]
That might be it. But than the following would be better:

``` php
add_filter( 'statify_skip_tracking', '__return_true' );
```

**Comment by Zodiac1978** [comment]
This does not make sense. If you don't want to track anything you wouldn't install the plugin at all.  It is an example for using a custom if statement to skip _some_ pages/posts.

After looking at it again I think there is just a closing parenthesis missing. That's all.

**Comment by patrickrobrecht** [comment]
The documentation of both hooks is in the [Wiki](https://github.com/pluginkollektiv/statify/wiki/Hooks). I'll translate the documentation.

**Comment by patrickrobrecht** [comment]
With PR https://github.com/pluginkollektiv/statify/pull/31 the links could just reference the plugin page https://wordpress.org/plugins/statify/.

**Comment by Zodiac1978** [comment]
After the merge from #31 we can replace the links with https://wordpress.org/plugins/statify/ like @patrickrobrecht suggested or we remove them completely.

**Comment by bueltge** [comment]
Remove them and link always to a valid documentation, the best in the same file, like readme.txt for wp.org or on github to the wiki. But different source are tasks for us, not always valid.

**Comment by bueltge** [comment]
@Zodiac1978 @patrickrobrecht 
Is that issue still relevant? I can't find wrong links in the source files and wiki?

**Comment by Zodiac1978** [comment]
Yes, it is. Updated line numbers are:
https://github.com/pluginkollektiv/statify/blob/master/inc/statify_frontend.class.php#L116
and
https://github.com/pluginkollektiv/statify/blob/master/inc/statify_dashboard.class.php#L27

**Comment by bueltge** [comment]
DANKE!

**Comment by Zodiac1978** [comment]
Thank YOU!
