### ISSUE TITLE
Update required WordPress and PHP versions for 2.0

### ISSUE THREAD

**Issue by stklcode** [pluginkollektiv/statify#253]
We have to raise the required WordPress and PHP versions according to the development state for the next release.
The final decision should be something reasonable, likely WP 5.x and PHP 5.6 or maybe 7.x. Can be postponed to the last responsible moment, just adding this issue to the milestone here, so we won’t forget about it.

Current requirements (up to 1.8.4):
WordPress 4.7
PHP 5.2

Incomplete list of merged, but unreleased changes:
#247 - add a library requiring PHP 5.3
#252 - introduces hooks that require WP 5.1

**Comment by florianbrinkmann** [comment]
I would be also fine with 5.3, but 5.6 or 7.x sounds better of course :)

@krafit @pfefferle

**Comment by Zodiac1978** [comment]
WP 5.1 is the last version which works with PHP <5.6. 

WP 5.2 requires PHP 5.6.

WP 4.1 is the first version which supports PHP 5.6.

So we could require PHP 5.3 and WP 5.1 without any problem.

See: https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

**Comment by stklcode** [comment]
PHP 7.2 & WP 5.1 it is, see #287
