### ISSUE TITLE
Period before and not after message

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#263]
<img width="445" alt="Bildschirmfoto 2023-06-08 um 15 25 55" src="https://github.com/pluginkollektiv/statify/assets/870475/7509146e-7fee-418a-857b-cd21494e4e3a">

This is because of a CSS issue:

`#statify_chart {
  color: #a7aaad;
  direction: rtl;
  text-align: center;
}`

This is wrong `direction: rtl` and is causing the issue.

Thanks to @Drivingralle for reporting it to me.

More context:
https://github.com/pluginkollektiv/statify/pull/101
https://github.com/pluginkollektiv/statify/commit/9c9fc3d29dd55ebc9f6314a0d1cf543da6c6b2ab

**Comment by stklcode** [comment]
Which version? 1.8.4 and/or latest snapshot?

For 1.8.4 it’s defined here:
https://github.com/pluginkollektiv/statify/blob/7b5d8ad03d28bad4dfd044ced75f45a34031f616/views/widget-front.php#L20

Now it is handled via JS and the texts are generated here:
https://github.com/pluginkollektiv/statify/blob/2ad7be47730090a944a67e1b7c857a2a78187592/inc/class-statify-dashboard.php#L140-L141

**Edit**
Overlooked the `rtl` part. Guess it should affect both versions.

**Comment by Zodiac1978** [comment]
> Which version? 1.8.4 and/or latest snapshot?

1.8.4 from the official directory. But if this at the same place the CSS issue still stands.

**Comment by Zodiac1978** [comment]
Current snapshot is failing due to error:

> Warning: require(/wp-content/plugins/statify/vendor/autoload.php): Failed to open stream: No such file or directory in /wp-content/plugins/statify/statify.php on line 57

**Comment by Zodiac1978** [comment]
If I disable this code `direction: rtl;` we could restore the right aligned layout of the labels wit this CSS:

```css
#statify_chart .ct-label.ct-vertical.ct-start {
  justify-content: flex-end;
}
```

Changing `flex-start` to `flex-end`.

Unfortunately the width is not enough and is cropping the label. Need to look why this happens. Maybe someone knows it and can chime in. Not sure how the width is calculated.

**Comment by Zodiac1978** [comment]
<img width="66" alt="Bildschirmfoto 2023-06-08 um 16 06 19" src="https://github.com/pluginkollektiv/statify/assets/870475/e5eb0c53-7f8c-4caa-a927-10592511c2c9">

**Comment by stklcode** [comment]
Hm, I can't tell any visual difference when simply moving the `direction: rtl` to the label group:
```diff
 #statify_chart {
        color: #a7aaad;
        flex: 0 0 100%;
-       direction: rtl;
        height: 140px;
        margin: 1em -0.5em;
        overflow-x: auto;
@@ -11,6 +10,10 @@
        text-align: center;
 }
 
+#statify_chart .ct-label {
+       direction: rtl;
+}
+
```

![statify-263-01](https://github.com/pluginkollektiv/statify/assets/12963621/3253f467-dab1-472f-8cb1-323c229b43ea)

**Comment by stklcode** [comment]
There is no visual difference when removing the direction and flex overrides completly. There is a proper label alignment in the Chartist CSS already...

```diff
 #statify_chart {
        color: #a7aaad;
        flex: 0 0 100%;
-       direction: rtl;
        height: 140px;
        margin: 1em -0.5em;
        overflow-x: auto;
@@ -16,13 +15,6 @@
        margin: 1em;
 }
 
-#statify_chart .ct-label.ct-vertical.ct-start {
-       -webkit-justify-content: flex-start;
-       justify-content: flex-start;
-       text-align: left;
-       text-anchor: start;
-}
-
```

![statify-263-01](https://github.com/pluginkollektiv/statify/assets/12963621/3253f467-dab1-472f-8cb1-323c229b43ea)

**Comment by stklcode** [comment]
Got it.

The `rtl` was introduced for scollable charts. Removing the stuff (previous comment) is visually identical, but the scrollbar is at the left end by default. With `rtl` it is right.

Could be resolved reverting the direction for all children of the container:
```css
#statify_chart * {
    direction: ltr;
}
```

**Comment by Zodiac1978** [comment]
But what if the locale is right-to-left? Like in Hebrew?

**Comment by stklcode** [comment]
Good point. Taken care of that in the PR:

```css
#statify_chart * {
	direction: ltr;
}

body.rtl #statify_chart * {
	direction: rtl;
}
```
