### ISSUE TITLE
Add basic spam protection if Antispam is not installed/active

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#27]
Antispam is protecting Statify for referrer spam. But what if Antispam ist not active/installed? Maybe we can add some basic spam protection to prevent Statify for being spammed with referrer spam.

**Comment by swissspidy** [comment]
See #11

**Comment by Zodiac1978** [comment]
@swissspidy I don't want to add a blacklist. ASB seems to have an automatic method for spam protection which helps Statify, so why not using this. I am just unable to find the reason why there is no referrer spam if I have ASB activated.

**Comment by Zodiac1978** [comment]
My original idea/question is:
Is there a way to prevent referrer spam without the maintenance work of a blacklist for every user?

ASB has some checks for trackbacks:
https://github.com/pluginkollektiv/antispam-bee/blob/fc14de14a4a06dc1dabcb960e95c64ec1a4e4107/antispam_bee.php#L1265-L1316

Empty referrer is not used anyway, fake ip check is not reliable (load balancer are reproducing false positives), bbcode check is not possible because we have no content, but **local db check** and the **blacklist check** could be implemented.

As an alternative we could use a centralized blacklist, like the [wordpress-comment-blacklist](https://github.com/splorp/wordpress-comment-blacklist)

**Comment by bueltge** [comment]
After longer chat about this topic. We should implement the simple check of ASB to use it without ASB - refrence to https://github.com/pluginkollektiv/antispam-bee/blob/fc14de14a4a06dc1dabcb960e95c64ec1a4e4107/antispam_bee.php#L1265-L1316 But wi should also a the WP default block list of the install, maybe the list is really helpful, if the user enhance this, maintain this, manually or automatically.

**Comment by bueltge** [comment]
Enhance readme for this topic, users have now the chance to maintain his blacklist via default, manually or via 3th plugin, like https://github.com/pluginkollektiv/blacklist-updater But we should add a hint about performance problems, if the list is big, a short and efficient list is much faster.

@Zodiac1978 maybe you can help me to enhance the readme?

**Comment by bueltge** [comment]
In my opinion is this ready for go live, only the documentation is an open task; maybe a help on your side with a better experience in the English language? @websupporter @patrickrobrecht

**Comment by websupporter** [comment]
I will have a look into this during the weekend :)

**Comment by bueltge** [comment]
Really great, ask me via slack if you have any questions!

**Comment by patrickrobrecht** [comment]
Documentation of the comment blacklist feature: https://github.com/pluginkollektiv/statify/tree/documentation-v1.5

**Comment by bueltge** [comment]
Also an another issue to close, great and thanks a lot @patrickrobrecht
