### ISSUE TITLE
Multisite with WordPress MU Domain Mapping plugin

### ISSUE THREAD

**Issue by jovilog** [pluginkollektiv/statify#30]
Nice to see that some of the multisite issues got [fixed](9). Thanks so much for that.
I'm the reporter of the [WordPress support topic](https://wordpress.org/support/topic/links-missing-subfolder-on-multisite/) @swissspidy linked to in [issue 9](9).

There's still a problem with the referrer stats. When using the WordPress MU Domain Mapping plugin on a multisite install (which is pretty common I think), there can be wrong referrer entries.

Valid referrer URLs are checked in `statify_frontend.class.php` on line 69 with `strpos( $referrer, home_url() ) === false`.

Calling a site URL that gets mapped to a different domain from an admin screen whose URL is unmapped currently qualifies as a valid stat entry since referrer (the admin screen) and `home_url()` (the website) don’t share the same domain. However, these cases should not get logged.

So probably, `$referrer` should be checked for not being `network_admin_url()`.

**Comment by bueltge** [comment]
WordPress supports different domains for different sites in the network in the core, the plugin MU Domain Mapping is only necessary, if you use alias for the domains. As small hint for the usage.

But ca you retrace the problem also on a install without this plugin, same problems?

**Comment by swissspidy** [comment]
The `home_url()` check fails because the site's domain is a completely custom one. So that bug  sounds reasonable.

**Comment by bueltge** [comment]
I think also to. But a bug, tranced without 3th party plugins is easier to debug. I have it on my list, maybe I fond time to debug it. Currently im not happy with the coding standards, my IDE have a lot of hints. ;)

**Comment by bueltge** [comment]
@swissspidy It would be fine if you can check the commit. I'm not sure that I have really understand the problem. Thanks!

**Comment by jovilog** [comment]
@bueltge The commit seems fine. However, I could not test it (in a dev multisite environment that is not quite up to date), because I got a fatal error calling the undefined function `apply_filters_deprecated()`. This was introduced in WordPress 4.6, but the plugin states it requires WordPress 3.9 or greater, i.e. it should work fine in my setup. So, either the documentation or the code needs further tweaks.
I hadn't the time to set up a multisite with custom domains and the latest WordPress.

**Comment by bueltge** [comment]
Thanks a lot for your feedback. `apply_filters_deprecated` - right, maybe I use other one or ask for the version.

**Comment by bueltge** [comment]
Have you @jovilog feedback about testing in the wild so that we can release this version? Thx.

**Comment by jovilog** [comment]
Sorry @bueltge, impossible for me to test this in the coming weeks.

**Comment by bueltge** [comment]
No problem, but thanks for your status.
