### ISSUE TITLE
Display-Error in Backend-Statistic

### ISSUE THREAD

**Issue by sebastianbrinkmann76** [pluginkollektiv/statify#32]
Since one of the last updates I always see a problem in the backend: The bubble is not placed right. Please fit it. :-)

Safari:
![bildschirmfoto 2016-10-27 um 08 35 01](https://cloud.githubusercontent.com/assets/23093207/19757041/f9ad66c0-9c20-11e6-9f53-a48d87712e55.png)

Chrome (on Mac)
![bildschirmfoto 2016-10-27 um 08 35 59](https://cloud.githubusercontent.com/assets/23093207/19757043/fcf983fe-9c20-11e6-9095-fdac27d1bec0.png)

**Comment by swissspidy** [comment]
Are you using Antispam Bee on your site?

**Comment by Zodiac1978** [comment]
If yes, this should be fixed in the current Github master after this pull request: https://github.com/pluginkollektiv/statify/pull/29 from @websupporter 

Could you try the Github version and report back if this fixes your issue?

**Comment by sebastianbrinkmann76** [comment]
Yes, thanks, this fixed the problem! :-)
