### ISSUE TITLE
Huge Statify Table

### ISSUE THREAD

**Issue by sebastianbrinkmann76** [pluginkollektiv/statify#33]
Hi guys,

I just saw that the mysql-table for statify has around 50 MByte of data. My blog has around 700 visits per day and I think that 50 MByte sounds to much. The dashboard widgets shows the last 30 days. Does it sound correct for you?

Thanks
Sebastian

**Comment by patrickrobrecht** [comment]
50 MB seems to be quite much if you only save the data for 30 days (only 21,000 entries then?). I've 11 MiB for ca. 135,000 rows in the Statify table of my WordPres installation.
Can you check the number of rows and whether rows older than the date period set for saving are deleted?

**Comment by sebastianbrinkmann76** [comment]
I have 375097 rows and I habe entries from 2015, so really to much. And I store them only 30 days. Sounds like the plugin doesn't delete old entries. And, yes, I run the cronjob every 5 minute. :-)

**Comment by Zodiac1978** [comment]
You can try https://wordpress.org/plugins/wp-crontrol/ and start the cron (statify_cleanup) manually. Does this cleanup your table?

**Comment by sebastianbrinkmann76** [comment]
I had WP Crontrol allready installed and this cron job wasn't listed. So I created it manually and now the statify Table has only 2,3 MByte. But, why this cronjob didn't exist before? 

Thank you zodiac1978!

**Comment by Zodiac1978** [comment]
Good to know, that it works! :)

Statify should have created the cronjob:
https://github.com/pluginkollektiv/statify/blob/7082e23c71e3d95dff3ee9e3ecb0703d4262b18a/inc/statify_install.class.php#L69-L76

I don't know why this does not happened on activation of the plugin.
