### ISSUE TITLE
Import data from wp statistics?

### ISSUE THREAD

**Issue by Olschiver** [pluginkollektiv/statify#60]
Hello,

is it possible to import statistics from wp statistics to statify?

Thanks for your help

**Comment by websupporter** [comment]
Hi @Olschiver,
I googled a bit, you mean https://de.wordpress.org/plugins/wp-statistics/ right?

At least we do not have an import function for this data.

**Comment by Olschiver** [comment]
Hi @websupporter,

the link is right.
Is there any import function for statify?

wp statistics exports csv, tsv and xml format.

**Comment by websupporter** [comment]
No unfortunately.

Statify has no import function. Usually, the data in Statify is only saved for some days (you can customize the number of days), so importing data would only be a temporary thing, as the data after a while would get deleted.
