### ISSUE TITLE
Hook after data was added?

### ISSUE THREAD

**Issue by marbetschar** [pluginkollektiv/statify#61]
Is it possible to add a hook which is fired after Statify did insert new data to the db? Something like:

`do_action('statify_logged',$data);`

**Comment by bueltge** [comment]
Yes, should possible in this area https://github.com/pluginkollektiv/statify/blob/660a4041afe100adc7df4f010ac6989b88dd0ef4/inc/statify_frontend.class.php#L82

However, why? What is your goal with the hook. What will you see inside the var `$data`?

**Comment by marbetschar** [comment]
Sounds good!
 
Basically I'd love to track "Visitors" instead of simply "Page hits" - and still conform to the encouraged privacy laws Statify is promoting. If Statify would official support "Visitors", this would be awesome!
 
To make this happen we need some sort of session - without using Cookies and without storing IP addresses in the database and without passing a session id on every request via URL. This limits the possibilities quite a bit - but it still can be done with some smart rules :)

However I can see this might be a tightrope walk measured on the principles of Statify - and because of this it might be too difficult to explain how this is done while still conforming to the laws. In case this is something Statify don't want to officially support, it would be awesome to have this sort of hook as an extension point to enrich the data where needed - where `$data` should contain the data inserted to the database - including primary key.

**To make a long story short: I'd love to see support for "Visitors" in Statify, can you please add it? :)**

**Comment by websupporter** [comment]
> Can Statify support "Visitors"

I can't speak for the whole team, but for me it looks like a huge burden. Not only which solid method could be used, which conforms with the privacy principles, but also, what does count as a "visitor". I think we would enter quite a territory with huge ambiguity.

That said, to provide some hooks and filter to allow 3rd parties to follow this path is something I would really love to see. I think the way suggested by @marbetschar sounds valid:

```
$result = $wpdb->insert( $wpdb->statify, $data );
if ( $result ) {
 do_action( 'statify-db-insert-action-naming-is-important', $wpdb->last_insert_id, $data );
}
```

https://github.com/pluginkollektiv/statify/blob/660a4041afe100adc7df4f010ac6989b88dd0ef4/inc/statify_frontend.class.php#L80-L83

Maybe the `if` conditional is not necessary, but this is up to the PR I guess :)

**Comment by krafit** [comment]
> I can't speak for the whole team, but for me it looks like a huge burden. Not only which solid method could be used, which conforms with the privacy principles, but also, what does count as a "visitor". I think we would enter quite a territory with huge ambiguity.

Agreed!

**Comment by stklcode** [comment]
> Basically I'd love to track "Visitors" instead of simply "Page hits" - and still conform to the encouraged privacy laws Statify is promoting. If Statify would official support "Visitors", this would be awesome!

If you want to use the same data structure as Statify to track "visitors" instead of visits, you might simply use the existing `statify__skip_tracking` hook and skip tracking, if your "session"-metric recognizes a user withouf changing anything in Statify at all. (reduces the overhead of removing the entry afterwards)

So if you don't wanna extend the data by an additional vitistor-tracking, I can't see the need for another hook here.

Probably most simple approach could be excluding internal referers, that's what I've done on several sites with my blacklist extension (don't wanna advertise it here, just figure out possibilities).
With the same idea you might also not skip tracking, but add an additional evaluation to the dashboard widget that excludes those entries (referer is stored in DB).

**Comment by websupporter** [comment]
Thanks for the additional input @krafit @stklcode 

> So if you don't wanna extend the data by an additional vitistor-tracking, I can't see the need for another hook here.

This would be the use case in my eyes. You could add another table for the visitors and create logs, which track the click through path e.g. To do so, you can now hook in like 

```
add_action( 'statify__visit_saved', function( $visit_id, $data ) {

 // my own magic stuff.
}, 10, 2 );

Therefore I will close the ticket. Thanks for your suggestion and help @marbetschar
