### ISSUE TITLE
How to extend the charts?

### ISSUE THREAD

**Issue by marbetschar** [pluginkollektiv/statify#65]
Thank you for adding the new `statify__visit_saved` hook.

Now I'd love to add a new table, storing the user session for a given page visit. For this I plan to store the following information:

```
$statify_id = ...;
$user_hash = crypt(CRYPT_SHA512, $_SERVER['REMOTE_ADDR'] . $_SERVER['HTTP_USER_AGENT'], $salt);
$timestamp = time();
$session_id = uniqid();
```

And then simply check if the `$user_hash` was active within the last 30mins, and if so use the `$session_id` which was used earlier. Otherwise I'll use the newly created `$session_id` as seen above.

In this scenario I'll be able to join the Statfiy table with mine and make a grouping on `$session_id` to get the amount of visitors. But how to add this information to the existing charts? And/or how to add new charts?

**Comment by websupporter** [comment]
Hi @marbetschar,
I would suggest to decouple here from Statify and maybe serve a dashboard widget (or a whole admin page) by your own.
