### ISSUE TITLE
Widget: Y axis label only shows last two digits

### ISSUE THREAD

**Issue by abrain** [pluginkollektiv/statify#73]
The label of the Y axis gets cut off, when the number is too long. As you can see in the picture it should read 1599, but you only see the last two digits.

![bildschirmfoto 2018-03-14 um 17 55 35](https://user-images.githubusercontent.com/1263052/37418136-cbbe7218-27b1-11e8-89cb-7783042ea2be.png)

**Comment by stklcode** [comment]
Thanks for reporting. This is related to the fixed label-size of the new chart libaray in 1.6.0. The label does not automatically grow.

PR present to fix this.

**Comment by patrickrobrecht** [comment]
@abrain The issue will be fixed in the next release.

**Comment by abrain** [comment]
Wow, that was quick 😄 Thanks!

**Comment by bueltge** [comment]
@patrickrobrecht Is this fix live on wp.org SVN?

**Comment by patrickrobrecht** [comment]
@bueltge Not yet. The last three commits to master are not on wp.org SVN. I think that we should merge some more things before the next release: #75 is ready as well, but I was waiting for a final decision on #72.

**Comment by bueltge** [comment]
Thanks for your fast reply.
