### ISSUE TITLE
Show search terms

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#76]
Is it possible to get the referrer information to additionally show search terms which are used to find the site?

**Comment by stklcode** [comment]
Possible, if full search engine referrer is present. Could be implemented for the major search engines without much effort.

Some decisions have to be made first though:
* Extract on the fly, on widget generation or asynchronous? Requires some matching and parsing, so I'd prefer a non-blocking method with respect to performance.
* Persist in additional DB field (not necessary if otf) or in temporary data cache?
* Cleanup, i.e list distinct case insensitive? (definitely IMHO)

I would prefer a lazy-loading approach, calculate on Widget call for new lines and persist for future use.

**Comment by websupporter** [comment]
As far as I am informed, some years ago it was possible to extract the keywords from the Referer, but Google et.al. changed this behavior. I did a quick test with Google and Bing and the Referer-URL was google.com and bing.com, but not the full URL with the keywords in it.

What we could do: What is searched on the site (example.com?s=searchterm) and extract those keywords. These might be interesting as well.

For me the question would be, how to fit all those new information into the tiny dashboard widget.

**Comment by Zodiac1978** [comment]
Related: https://googleblog.blogspot.de/2011/10/making-search-more-secure.html

**Comment by patrickrobrecht** [comment]
I did a small evaluation on my site with the most entries in the Statify table:
- For referrers from from `google.(com|de|...)` only 15 out of 6.010 entries logged in 2018 contain a search keyword.
- For referrers from `bing.com` the search keyword is present in every third case, for the 2018 entries even less (10 %, all others `https://www.bing.com/`).

By default, searches on the site are not logged by Statify (https://github.com/pluginkollektiv/statify/blob/master/inc/statify_frontend.class.php#L149) - so this does not make sense as long as the default skip tracking setting remains unchanged.

**Comment by Zodiac1978** [comment]
> For me the question would be, how to fit all those new information into the tiny dashboard widget.

For example like Jetpack Stats:
![bildschirmfoto 2018-09-17 um 17 56 06](https://user-images.githubusercontent.com/870475/45634580-09b39600-baa3-11e8-83cb-d57469a03bbd.png)

> so this does not make sense as long as the default skip tracking setting remains unchanged.

How about making this an option to enable internal search tracking?

**Comment by patrickrobrecht** [comment]
There are other plugins for tracking of internal searches (e. g. [Search Meter](https://wordpress.org/plugins/search-meter/) - [GitHub](https://github.com/bennettmcelwee/Search-Meter)). That's why I'm not sure whether that should be integrated into Statify.

**Comment by Zodiac1978** [comment]
If I summarize the discussion so far: We are not getting very much referrer information with search terms and per default we are not tracking any internal searches at the moment, but there are plugins which are doing just this.
So I think we can close this issue. If someone thinks we should implement one of these feature nevertheless please re-open this ticket or open a new issue for this feature!
