### ISSUE TITLE
Add widget for displaying stats in frontend

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#79]
Maybe something like the dashboard widget or this plugin https://de.wordpress.org/plugins/statify-widget/

**Comment by websupporter** [comment]
Since there is already a plugin out there for this task, I think we are good.

**Comment by Zodiac1978** [comment]
Closing this issue as there is a great working plugin already there. We could re-open this ticket if the plugin is not maintained anymore or Finn Dohrn wants to merge his plugin into Statify. :)
