### ISSUE TITLE
Wiki page with 3rd party extensions

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/statify#80]
Coming from #79 

Statify is a slim plugin, which serves the user a simple purpose: Show me a graph of the last days, how many visits did I have and which URLs have been visited. If you compare this to Piwik or GA, this is not a lot of information. And a lot of different informations and visualisations could actually be done with the data Statify is generating.

To put all those ideas into Statify could potentially mean to bloat Statify and loose its coherence. On the other side, there are some 3rd party plugins, which use the data generated by Statify for other purposes.

Instead of incorporating more and more functionality, it might be a good idea to collect all those in a separate wiki page and draw the users attention to this page like

> If you are interested in more insights, have a look at those great plugins, which extend the functionality of Statify

Such a text in the widget with a link would be useful I think.

Two plugins I know of:
* https://de.wordpress.org/plugins/statify-widget/
* https://github.com/patrickrobrecht/extended-evaluation-for-statify

If there are more extensions out there, such a link might draw also the developers attention to it and they might contact us to add their plugins or scripts as well. Maybe from #61 there might be something in the making in the near future as well (cc @marbetschar)?

**Comment by patrickrobrecht** [comment]
Currently we list the extension plugins in the readme.txt such that it is translateable on wordpress.org: see FAQ on https://de.wordpress.org/plugins/statify/

**Comment by websupporter** [comment]
Ah! Thanks @patrickrobrecht, I was not aware of this section.
