### ISSUE TITLE
Wrong Counter on dashboard

### ISSUE THREAD

**Issue by bueltge** [pluginkollektiv/statify#81]
I get this info via mail to this wrong counter on top left; maybe we can validate.

![screenshot-2018-3-30 dashboard hastenichgesehen wordpress](https://user-images.githubusercontent.com/133425/38149175-d2220804-3459-11e8-809a-da89d49a5167.png)

**Comment by patrickrobrecht** [comment]
I assume that this is fixed in master: see https://github.com/pluginkollektiv/statify/issues/73

**Comment by bueltge** [comment]
Closed, fixed for now and in the next release ready to use.
