### ISSUE TITLE
Display error in dashboard widget

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#82]
> I noticed a display error of the number of views in the left top corner:
> 
> https://jumpshare.com/v/kB6Xl5yMEz3ByzxMMk9r
> 
> Actually in this example it should display “8848”, but because the container is to small it just displays “48”.

Reported here: https://wordpress.org/support/topic/display-error-views-left-top-corner/

**Comment by bueltge** [comment]
like #81 , fixed in #73
