### ISSUE TITLE
Multisite incompatibilities

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/statify#9]
I just tried activating the plugin network-wide. Even after I had visited each site's dashboard, no database tables were created.

Not sure if it's my fault or there's something wrong in the plugin, but it may be worth exploring. Other users reported multisite incompatibilities as well:

https://wordpress.org/support/topic/links-missing-subfolder-on-multisite?replies=9#post-7074398

**Comment by Zodiac1978** [comment]
I can confirm the problem. "Na data available" showing for days after being network-activated. After activating per site it shows data.

**Comment by glueckpress** [comment]
Confirmed from memory. We should add this piece of info to the readme, preferably in _FAQ_.

**Comment by swissspidy** [comment]
Even better: We fix it :)

**Comment by te-online** [comment]
I know it is not long ago, but: Did you fix it already? ;-)

https://github.com/pluginkollektiv/statify/blob/master/inc/statify_install.class.php#L27
That looks like it should work, doesn't it? But in my multisite-environment there are no statify tables created either.

**Comment by te-online** [comment]
Okay, I tried a fix, but don't ask me what it's about :laughing: 

I changed the install method https://github.com/pluginkollektiv/statify/blob/master/inc/statify_install.class.php#L32

```
/* Neuer MU-Blog */
        if ( ! empty($id) ) {
            /* Im Netzwerk? */
            if ( is_plugin_active_for_network(STATIFY_BASE) ) {
                 /* Wechsel */
                 switch_to_blog( (int)$id );
                 /* Installieren */
                 self::_apply();
                 /* Wechsel zurück */
                 restore_current_blog();
                 /* Raus */
                 return;
            }
        }
```

I removed the _return_ when the plugin is not active for network and instead wrapped it with the if statement.
Maybe the install function is called multiple times when activating network-wide, I don't know. This way the code after this snippet was executed on activation and all the tables were created.

The fix might have the side effect that the original purpose of activating the plugin for new blogs might not work now...

@sergejmueller Maybe this helps you a tiny bit with fixing it :wink:

**Comment by swissspidy** [comment]
@te-online Multisite plugin activation is quite difficult from normal plugin activation, with lots of edge-cases. I hope this is the solution and will check out your proposed fix.

**Comment by te-online** [comment]
@swissspidy To be honest, I think there is a high chance that this is not the correct solution. I didn't fully understand what the first part is used for and when it gets called. I didn't do debugging, just some quick guessing. I only treated the symptom, but not the source of the problem, so to say. 

Chances are, that maybe $id is not empty at all but is supposed to be. Or maybe the order of the code is just wrong. Maybe this if(empty($id)) {} statement should be placed after the activation code for network-wide, so the return won't cancel the function too early.

**Comment by Berlinicker** [comment]
I had the same problem. Having installed Multisite and Statify, Statify did show "No data available". The problem existed independantly from the widget configuration. Apparently there are incompatibilities between both plugins.

I fixed it with the help of a wordpress expert. He found out that Statify did not create a data base table in phpMyAdmin because of Multisite. So we created the data base table wp_statify manually, he sent it to me via email and I imported it into phpMyAdmin. Finally, Statify started showing results.

Unfortunately, the solution did not work for my second domain which I manage with Multisite, although I added the data base table wp_statify to my second data base on my web server. Does anybody have an explanation for what reason Statify does not work for my second domain? May it be related to Domain Mapping? 

Thanks in advance for some clues!

**Comment by swissspidy** [comment]
@Berlinicker Thanks for chiming in. This ticket is all about multisite incompatibilities and the missing database tables. I hope to find some time this spring to work on it.

Out of the blue I can't say anything about your second website. Have you added only 1 table or 1 for every blog? (Not sure what Statify requires at the moment). Domain mapping _could_ be a culprit here, but I'd need to test it.

**Comment by te-online** [comment]
@Berlinicker Are you sure, you've got the prefixes right? Maybe you have set up a different prefix for this installation than `wp_`?

**Comment by Berlinicker** [comment]
@swissspidy and @te-online Thanks for the quick responses. It is great that you are going to fix the problem. 

In fact, I have added only one table to the main data base which corresponds to my wp-config.php. My second data base seems to be for something else than my second domain, so adding the table to the second data base did not change anything. Should I add another table to the main data base which corresponds to my wp-config.php? Which prefix do I have to use in that case? 
(@te-online: The prefix is always "wp_".)

Thanks in advance!

**Comment by te-online** [comment]
@Berlinicker As far as I know, with multisite, you should have a db structure like this:

`prefix` _ `empty for first or blognumber` _ `table name`
e.g.
wp_postmeta
wp_posts
wp_2_postmeta
wp_2_posts
`...`

To be clear, all the tables are in one database with multisite per default. WordPress can only access databases, that are specified in wp-config.php.

Considering this, you would need a statify table for each of your multisite sites.
- wp_statify
- wp_2_statify

**Comment by Berlinicker** [comment]
@te-online That's it! Now it works. Thanks a lot for your help! Thanks to WordPress expert Finn Dohrn from bit01, too! http://www.bit01.de/. That was a remarkable service!

**Comment by herpaderpaldent** [comment]
Is there an ETA on a Plugin Version that handels this issue? 

Or a HowTo Article how to achive statify working on Multisite?

**Comment by swissspidy** [comment]
@huberfe Thanks for asking.

As I said in January, I was hoping to have some time this spring to fix this issue. Spring is now, so give me a few weeks to look into this, i.e. until end of May. If anyone's able to help earlier, feel free to jump in and submit a PR.

**Comment by herpaderpaldent** [comment]
merci dir

**Comment by Zodiac1978** [comment]
@swissspidy Any news on this?

**Comment by swissspidy** [comment]
@Zodiac1978 Sorry, no update means no progress. But since you asked, I finally took an hour to look at it. #23 should fix this.

Perhaps need to adjust version numbers in the inline docs though :)

As I'm normally not using Statify, someone else needs to test and merge this.

Thanks.

**Comment by te-online** [comment]
Just tested on a multisite installation and it worked! Thank you for fixing it.

**Comment by swissspidy** [comment]
I think #23 only fixes parts of the multisite issues. The one with the permalinks mentioned in the issue description is still unfixed IIRC.

**Comment by te-online** [comment]
That should be a quick fix, since it's only the output rendering, right? Maybe I can look into that later.

Edit: Actually, that seems to be fixed. On my test installation it works as expected. (You're talking about that one, are you? https://wordpress.org/support/topic/links-missing-subfolder-on-multisite?replies=9#post-7074398)

**Comment by swissspidy** [comment]
Yes, I'm talking about that one.

Apparently I already fixed it last year, see c7206233e6da28ae0b95a543748dfdda8e113634 😄

Therefore closing this issue.

**Comment by Zodiac1978** [comment]
Just for completeness:
This https://github.com/pluginkollektiv/statify/commit/c7206233e6da28ae0b95a543748dfdda8e113634 also fixes the same issue with subfolder installs.

And you can workaround the activation issue if you activate the plugin on each site separately.

**Comment by swissspidy** [comment]
@Zodiac1978 No need for that workaround anymore as this bug should be fixed after merging #23.

Edit: Or am I missing something?

**Comment by Zodiac1978** [comment]
> @Zodiac1978 No need for that workaround anymore as this bug should be fixed after merging #23.

That's why I wrote "just for completeness" - I just wanted to mention this workaround here. In case someone is stuck on an old version and might want to know it. ;)

**Comment by ouun** [comment]
As I'm activating the plugin on a MultiSite with > 1500 sites the tables are not created. Until now I was not able to figure out why not and as soon as I activate it for a single site in the network, the wp_X_statify table is perfectly added to the DB.

**Comment by te-online** [comment]
@ouun Did you check you server logs, whether you might be running into a timeout with switching to 1500 blogs and running a single `CREATE TABLE` query? If you output `$sites` in https://github.com/pluginkollektiv/statify/blob/master/inc/class-statify-install.php#L32, does it give you an array of all your 1500 sites? Also, try logging here https://github.com/pluginkollektiv/statify/blob/master/inc/class-statify-install.php#L39, does it log 1500 entries – for each site one?

Looking forward to your report 😉
