### ISSUE TITLE
Add email notifications for statistics data

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#99]
First asked here: https://wordpress.org/support/topic/2-suggestions-5/

> And an option would be really nice to get a mail with the statistic data every hour / once a day / once a week.

**Comment by stklcode** [comment]
:-1: from me

Seems overdone for most users. Also various open questions:
* Who receives the mail (admin, site-admin, configurable?)
* What is sent (single values per day, aggregated value,  top-lists, ...)
* How is the data presented? (plain text, HTML table, embedded pre-rendered SVG graphics, ...)

I'd vote this to a separate extension plugin, probably as a feature for _Extended Evaluation_ or similar.

**Comment by patrickrobrecht** [comment]
I agree with @stklcode that email notifications seem to be overdone for most users. I think a separate _Statify Email Notifications_ plugin would be the right place for this feature.
